CREATE TABLE IF NOT EXISTS `quit` (
  `id` varchar(128) DEFAULT NULL comment 'id',
  `knight_id` varchar(128) DEFAULT NULL comment '骑士id',
  `commit_time` datetime DEFAULT NULL comment '提交时间',
  `quit_time` datetime DEFAULT NULL comment '离职时间',
  `quit_reason` varchar(128) DEFAULT NULL comment '离职原因',
  `state` varchar(128) DEFAULT NULL comment '状态',
  `examine` varchar(128) DEFAULT NULL comment '审核',
  `delstatus` varchar(128) DEFAULT NULL comment 'delstatus',
  `creatorId` varchar(128) DEFAULT NULL comment 'creatorId',
  `creatorName` varchar(128) DEFAULT NULL comment 'creatorName',
  `superOrg_id` varchar(128) DEFAULT NULL comment '所属公司id',
  `superOrg_name` varchar(128) DEFAULT NULL comment '所属公司名称',
  `fulldept_id` varchar(128) DEFAULT NULL comment '全部门路径id',
  `fulldept_name` varchar(128) DEFAULT NULL comment '全部门路径名',
  `fullpost_id` varchar(128) DEFAULT NULL comment '全岗位路径id',
  `fullpost_name` varchar(128) DEFAULT NULL comment '全岗位路径名',
  `org_code` varchar(128) DEFAULT NULL comment '组织机构代码',
  `createTime` datetime DEFAULT NULL comment 'createTime',
  `modifiedTime` datetime DEFAULT NULL comment 'modifiedTime'
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
CREATE TABLE IF NOT EXISTS `quit_log` (
  `id` varchar(128) DEFAULT NULL comment 'id',
  `quit_id` varchar(128) DEFAULT NULL comment '离职id',
  `chuliren_id` varchar(128) DEFAULT NULL comment '处理人id',
  `shenpi_opinions` varchar(128) DEFAULT NULL comment '审批意见',
  `operation` varchar(128) DEFAULT NULL comment '操作',
  `delstatus` varchar(128) DEFAULT NULL comment 'delstatus',
  `creatorId` varchar(128) DEFAULT NULL comment 'creatorId',
  `creatorName` varchar(128) DEFAULT NULL comment 'creatorName',
  `superOrg_id` varchar(128) DEFAULT NULL comment '所属公司id',
  `superOrg_name` varchar(128) DEFAULT NULL comment '所属公司名称',
  `fulldept_id` varchar(128) DEFAULT NULL comment '全部门路径id',
  `fulldept_name` varchar(128) DEFAULT NULL comment '全部门路径名',
  `fullpost_id` varchar(128) DEFAULT NULL comment '全岗位路径id',
  `fullpost_name` varchar(128) DEFAULT NULL comment '全岗位路径名',
  `org_code` varchar(128) DEFAULT NULL comment '组织机构代码',
  `createTime` datetime DEFAULT NULL comment 'createTime',
  `modifiedTime` datetime DEFAULT NULL comment 'modifiedTime'
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
CREATE TABLE IF NOT EXISTS `leave1` (
  `id` varchar(128) DEFAULT NULL comment 'id',
  `knight_id` varchar(128) DEFAULT NULL comment '骑士id',
  `commit_time` datetime DEFAULT NULL comment '提交时间',
  `leave_startTime` datetime DEFAULT NULL comment '请假开始时间',
  `leave_endTime` datetime DEFAULT NULL comment '请假结束时间',
  `leave_totalDay` decimal(15,2) DEFAULT NULL comment '请假总计天数',
  `leave_reason` varchar(128) DEFAULT NULL comment '请假原因',
  `state` varchar(128) DEFAULT NULL comment '状态',
  `examine` varchar(128) DEFAULT NULL comment '审核',
  `delstatus` varchar(128) DEFAULT NULL comment 'delstatus',
  `creatorId` varchar(128) DEFAULT NULL comment 'creatorId',
  `creatorName` varchar(128) DEFAULT NULL comment 'creatorName',
  `superOrg_id` varchar(128) DEFAULT NULL comment '所属公司id',
  `superOrg_name` varchar(128) DEFAULT NULL comment '所属公司名称',
  `fulldept_id` varchar(128) DEFAULT NULL comment '全部门路径id',
  `fulldept_name` varchar(128) DEFAULT NULL comment '全部门路径名',
  `fullpost_id` varchar(128) DEFAULT NULL comment '全岗位路径id',
  `fullpost_name` varchar(128) DEFAULT NULL comment '全岗位路径名',
  `org_code` varchar(128) DEFAULT NULL comment '组织机构代码',
  `createTime` datetime DEFAULT NULL comment 'createTime',
  `modifiedTime` datetime DEFAULT NULL comment 'modifiedTime'
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
CREATE TABLE IF NOT EXISTS `leave1_log` (
  `id` varchar(128) DEFAULT NULL comment 'id',
  `leave_id` varchar(128) DEFAULT NULL comment '请假id',
  `chuliren_id` varchar(128) DEFAULT NULL comment '处理人id',
  `shenpi_opinions` varchar(128) DEFAULT NULL comment '审批意见',
  `operation` varchar(128) DEFAULT NULL comment '操作',
  `delstatus` varchar(128) DEFAULT NULL comment 'delstatus',
  `creatorId` varchar(128) DEFAULT NULL comment 'creatorId',
  `creatorName` varchar(128) DEFAULT NULL comment 'creatorName',
  `superOrg_id` varchar(128) DEFAULT NULL comment '所属公司id',
  `superOrg_name` varchar(128) DEFAULT NULL comment '所属公司名称',
  `fulldept_id` varchar(128) DEFAULT NULL comment '全部门路径id',
  `fulldept_name` varchar(128) DEFAULT NULL comment '全部门路径名',
  `fullpost_id` varchar(128) DEFAULT NULL comment '全岗位路径id',
  `fullpost_name` varchar(128) DEFAULT NULL comment '全岗位路径名',
  `org_code` varchar(128) DEFAULT NULL comment '组织机构代码',
  `createTime` datetime DEFAULT NULL comment 'createTime',
  `modifiedTime` datetime DEFAULT NULL comment 'modifiedTime'
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
