CREATE TABLE IF NOT EXISTS `warehouse` (
  `id` varchar(128) DEFAULT NULL comment '仓库id',
  `warehouse_number` varchar(128) DEFAULT NULL comment '仓库编码',
  `warehouse_name` varchar(128) DEFAULT NULL comment '仓库名称',
  `belong_city` varchar(128) DEFAULT NULL comment '所属城市',
  `remarks` varchar(128) DEFAULT NULL comment '备注',
  `delstatus` varchar(128) DEFAULT NULL comment 'delstatus',
  `creatorId` varchar(128) DEFAULT NULL comment 'creatorId',
  `creatorName` varchar(128) DEFAULT NULL comment 'creatorName',
  `superOrg_id` varchar(128) DEFAULT NULL comment '所属公司id',
  `superOrg_name` varchar(128) DEFAULT NULL comment '所属公司名称',
  `fulldept_id` varchar(128) DEFAULT NULL comment '全部门路径id',
  `fulldept_name` varchar(128) DEFAULT NULL comment '全部门路径名',
  `fullpost_id` varchar(128) DEFAULT NULL comment '全岗位路径id',
  `fullpost_name` varchar(128) DEFAULT NULL comment '全岗位路径名',
  `org_code` varchar(128) DEFAULT NULL comment '组织机构代码',
  `createTime` datetime DEFAULT NULL comment 'createTime',
  `modifiedTime` datetime DEFAULT NULL comment 'modifiedTime'
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
CREATE TABLE IF NOT EXISTS `ruku_manage` (
  `id` varchar(128) DEFAULT NULL comment 'id',
  `ruku_number` varchar(128) DEFAULT NULL comment '入库单号',
  `ruku_time` datetime DEFAULT NULL comment '入库时间',
  `warehouse_id` varchar(128) DEFAULT NULL comment '入库仓库id',
  `ruku_type` varchar(128) DEFAULT NULL comment '入库类型',
  `knight_id` varchar(128) DEFAULT NULL comment '归还骑士id',
  `remarks` varchar(128) DEFAULT NULL comment '备注',
  `storage_time` datetime DEFAULT NULL comment '实际入库时间',
  `operator_id` varchar(128) DEFAULT NULL comment '操作人id',
  `gonghao` varchar(128) DEFAULT NULL comment '工号',
  `state` varchar(128) DEFAULT NULL comment '状态',
  `delstatus` varchar(128) DEFAULT NULL comment 'delstatus',
  `creatorId` varchar(128) DEFAULT NULL comment 'creatorId',
  `creatorName` varchar(128) DEFAULT NULL comment 'creatorName',
  `superOrg_id` varchar(128) DEFAULT NULL comment '所属公司id',
  `superOrg_name` varchar(128) DEFAULT NULL comment '所属公司名称',
  `fulldept_id` varchar(128) DEFAULT NULL comment '全部门路径id',
  `fulldept_name` varchar(128) DEFAULT NULL comment '全部门路径名',
  `fullpost_id` varchar(128) DEFAULT NULL comment '全岗位路径id',
  `fullpost_name` varchar(128) DEFAULT NULL comment '全岗位路径名',
  `org_code` varchar(128) DEFAULT NULL comment '组织机构代码',
  `createTime` datetime DEFAULT NULL comment 'createTime',
  `modifiedTime` datetime DEFAULT NULL comment 'modifiedTime'
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
CREATE TABLE IF NOT EXISTS `ruku_materiel` (
  `id` varchar(128) DEFAULT NULL comment 'id',
  `ruku_id` varchar(128) DEFAULT NULL comment '入库单id',
  `materiel_id` varchar(128) DEFAULT NULL comment '物料id',
  `ruku_amount` decimal(15,2) DEFAULT NULL comment '入库数量',
  `delstatus` varchar(128) DEFAULT NULL comment 'delstatus',
  `creatorId` varchar(128) DEFAULT NULL comment 'creatorId',
  `creatorName` varchar(128) DEFAULT NULL comment 'creatorName',
  `superOrg_id` varchar(128) DEFAULT NULL comment '所属公司id',
  `superOrg_name` varchar(128) DEFAULT NULL comment '所属公司名称',
  `fulldept_id` varchar(128) DEFAULT NULL comment '全部门路径id',
  `fulldept_name` varchar(128) DEFAULT NULL comment '全部门路径名',
  `fullpost_id` varchar(128) DEFAULT NULL comment '全岗位路径id',
  `fullpost_name` varchar(128) DEFAULT NULL comment '全岗位路径名',
  `org_code` varchar(128) DEFAULT NULL comment '组织机构代码',
  `createTime` datetime DEFAULT NULL comment 'createTime',
  `modifiedTime` datetime DEFAULT NULL comment 'modifiedTime'
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
CREATE TABLE IF NOT EXISTS `stock` (
  `id` varchar(128) DEFAULT NULL comment 'id',
  `warehouse_id` varchar(128) DEFAULT NULL comment '仓库id',
  `material_id` varchar(128) DEFAULT NULL comment '物料id',
  `stock_amount` decimal(15,2) DEFAULT NULL comment '库存数量',
  `delstatus` varchar(128) DEFAULT NULL comment 'delstatus',
  `creatorId` varchar(128) DEFAULT NULL comment 'creatorId',
  `creatorName` varchar(128) DEFAULT NULL comment 'creatorName',
  `superOrg_id` varchar(128) DEFAULT NULL comment '所属公司id',
  `superOrg_name` varchar(128) DEFAULT NULL comment '所属公司名称',
  `fulldept_id` varchar(128) DEFAULT NULL comment '全部门路径id',
  `fulldept_name` varchar(128) DEFAULT NULL comment '全部门路径名',
  `fullpost_id` varchar(128) DEFAULT NULL comment '全岗位路径id',
  `fullpost_name` varchar(128) DEFAULT NULL comment '全岗位路径名',
  `org_code` varchar(128) DEFAULT NULL comment '组织机构代码',
  `createTime` datetime DEFAULT NULL comment 'createTime',
  `modifiedTime` datetime DEFAULT NULL comment 'modifiedTime'
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
CREATE TABLE IF NOT EXISTS `diaobodan` (
  `id` varchar(128) DEFAULT NULL comment 'id',
  `chukuWarehouse_id` varchar(128) DEFAULT NULL comment '出货仓库id',
  `rukuWarehouse_id` varchar(128) DEFAULT NULL comment '入库仓库id',
  `allocation_time` datetime DEFAULT NULL comment '调拨日期',
  `diaoboren_id` varchar(128) DEFAULT NULL comment '调拨人id',
  `gonghao` varchar(128) DEFAULT NULL comment '工号',
  `remarks` varchar(128) DEFAULT NULL comment '备注',
  `allocation_status` varchar(128) DEFAULT NULL comment '调拨状态',
  `delstatus` varchar(128) DEFAULT NULL comment 'delstatus',
  `creatorId` varchar(128) DEFAULT NULL comment 'creatorId',
  `creatorName` varchar(128) DEFAULT NULL comment 'creatorName',
  `superOrg_id` varchar(128) DEFAULT NULL comment '所属公司id',
  `superOrg_name` varchar(128) DEFAULT NULL comment '所属公司名称',
  `fulldept_id` varchar(128) DEFAULT NULL comment '全部门路径id',
  `fulldept_name` varchar(128) DEFAULT NULL comment '全部门路径名',
  `fullpost_id` varchar(128) DEFAULT NULL comment '全岗位路径id',
  `fullpost_name` varchar(128) DEFAULT NULL comment '全岗位路径名',
  `org_code` varchar(128) DEFAULT NULL comment '组织机构代码',
  `createTime` datetime DEFAULT NULL comment 'createTime',
  `modifiedTime` datetime DEFAULT NULL comment 'modifiedTime'
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
CREATE TABLE IF NOT EXISTS `diaobo_materiel` (
  `id` varchar(128) DEFAULT NULL comment 'id',
  `diaobodan_id` varchar(128) DEFAULT NULL comment '调拨单id',
  `materiel_id` varchar(128) DEFAULT NULL comment '物料id',
  `ruku_amount` decimal(15,2) DEFAULT NULL comment '入库数量',
  `delstatus` varchar(128) DEFAULT NULL comment 'delstatus',
  `creatorId` varchar(128) DEFAULT NULL comment 'creatorId',
  `creatorName` varchar(128) DEFAULT NULL comment 'creatorName',
  `superOrg_id` varchar(128) DEFAULT NULL comment '所属公司id',
  `superOrg_name` varchar(128) DEFAULT NULL comment '所属公司名称',
  `fulldept_id` varchar(128) DEFAULT NULL comment '全部门路径id',
  `fulldept_name` varchar(128) DEFAULT NULL comment '全部门路径名',
  `fullpost_id` varchar(128) DEFAULT NULL comment '全岗位路径id',
  `fullpost_name` varchar(128) DEFAULT NULL comment '全岗位路径名',
  `org_code` varchar(128) DEFAULT NULL comment '组织机构代码',
  `createTime` datetime DEFAULT NULL comment 'createTime',
  `modifiedTime` datetime DEFAULT NULL comment 'modifiedTime'
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
CREATE TABLE IF NOT EXISTS `chuku_manage` (
  `id` varchar(128) DEFAULT NULL comment 'id',
  `chuku_number` varchar(128) DEFAULT NULL comment '出库单号',
  `chuku_time` datetime DEFAULT NULL comment '出库时间',
  `warehouse_id` varchar(128) DEFAULT NULL comment '出库仓库id',
  `issuer_id` varchar(128) DEFAULT NULL comment '发放人id',
  `gonghao_one` varchar(128) DEFAULT NULL comment '工号1',
  `shiyong_id` varchar(128) DEFAULT NULL comment '使用人id',
  `gonghao_two` varchar(128) DEFAULT NULL comment '工号2',
  `material_id` varchar(128) DEFAULT NULL comment '物料id',
  `Issue_amount` decimal(15,2) DEFAULT NULL comment '发放数量',
  `delstatus` varchar(128) DEFAULT NULL comment 'delstatus',
  `creatorId` varchar(128) DEFAULT NULL comment 'creatorId',
  `creatorName` varchar(128) DEFAULT NULL comment 'creatorName',
  `superOrg_id` varchar(128) DEFAULT NULL comment '所属公司id',
  `superOrg_name` varchar(128) DEFAULT NULL comment '所属公司名称',
  `fulldept_id` varchar(128) DEFAULT NULL comment '全部门路径id',
  `fulldept_name` varchar(128) DEFAULT NULL comment '全部门路径名',
  `fullpost_id` varchar(128) DEFAULT NULL comment '全岗位路径id',
  `fullpost_name` varchar(128) DEFAULT NULL comment '全岗位路径名',
  `org_code` varchar(128) DEFAULT NULL comment '组织机构代码',
  `createTime` datetime DEFAULT NULL comment 'createTime',
  `modifiedTime` datetime DEFAULT NULL comment 'modifiedTime'
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
