CREATE TABLE IF NOT EXISTS `materiel_Apply` (
  `id` varchar(128) DEFAULT NULL comment 'id',
  `materiel_Apply_number` varchar(128) DEFAULT NULL comment '物资单号',
  `apply_people_id` varchar(128) DEFAULT NULL comment '申请人id',
  `apply_time` datetime DEFAULT NULL comment '申请时间',
  `belong_city` varchar(128) DEFAULT NULL comment '所属城市',
  `apply_explain` varchar(128) DEFAULT NULL comment '申请说明',
  `state` varchar(128) DEFAULT NULL comment '状态',
  `examine` varchar(128) DEFAULT NULL comment '审核',
  `release_status` varchar(128) DEFAULT NULL comment '发放状态',
  `delstatus` varchar(128) DEFAULT NULL comment 'delstatus',
  `creatorId` varchar(128) DEFAULT NULL comment 'creatorId',
  `creatorName` varchar(128) DEFAULT NULL comment 'creatorName',
  `superOrg_id` varchar(128) DEFAULT NULL comment '所属公司id',
  `superOrg_name` varchar(128) DEFAULT NULL comment '所属公司名称',
  `fulldept_id` varchar(128) DEFAULT NULL comment '全部门路径id',
  `fulldept_name` varchar(128) DEFAULT NULL comment '全部门路径名',
  `fullpost_id` varchar(128) DEFAULT NULL comment '全岗位路径id',
  `fullpost_name` varchar(128) DEFAULT NULL comment '全岗位路径名',
  `org_code` varchar(128) DEFAULT NULL comment '组织机构代码',
  `createTime` datetime DEFAULT NULL comment 'createTime',
  `modifiedTime` datetime DEFAULT NULL comment 'modifiedTime'
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
CREATE TABLE IF NOT EXISTS `apply_materiel` (
  `id` varchar(128) DEFAULT NULL comment 'id',
  `materiel_apply_id` varchar(128) DEFAULT NULL comment '物料申请id',
  `materiel_id` varchar(128) DEFAULT NULL comment '物料id',
  `apply_amount` decimal(15,2) DEFAULT NULL comment '申请数量',
  `fafang_amount` decimal(15,2) DEFAULT NULL comment '发放数量',
  `shiyong_id` varchar(128) DEFAULT NULL comment '使用人id',
  `delstatus` varchar(128) DEFAULT NULL comment 'delstatus',
  `creatorId` varchar(128) DEFAULT NULL comment 'creatorId',
  `creatorName` varchar(128) DEFAULT NULL comment 'creatorName',
  `superOrg_id` varchar(128) DEFAULT NULL comment '所属公司id',
  `superOrg_name` varchar(128) DEFAULT NULL comment '所属公司名称',
  `fulldept_id` varchar(128) DEFAULT NULL comment '全部门路径id',
  `fulldept_name` varchar(128) DEFAULT NULL comment '全部门路径名',
  `fullpost_id` varchar(128) DEFAULT NULL comment '全岗位路径id',
  `fullpost_name` varchar(128) DEFAULT NULL comment '全岗位路径名',
  `org_code` varchar(128) DEFAULT NULL comment '组织机构代码',
  `createTime` datetime DEFAULT NULL comment 'createTime',
  `modifiedTime` datetime DEFAULT NULL comment 'modifiedTime'
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
CREATE TABLE IF NOT EXISTS `apply_processlog` (
  `id` varchar(128) DEFAULT NULL comment 'id',
  `materiel_apply_id` varchar(128) DEFAULT NULL comment '物料申请id',
  `chuliren_id` varchar(128) DEFAULT NULL comment '处理人id',
  `operation_time` datetime DEFAULT NULL comment '操作时间',
  `action` varchar(128) DEFAULT NULL comment '动作',
  `examine_opinion` varchar(128) DEFAULT NULL comment '审批意见',
  `delstatus` varchar(128) DEFAULT NULL comment 'delstatus',
  `creatorId` varchar(128) DEFAULT NULL comment 'creatorId',
  `creatorName` varchar(128) DEFAULT NULL comment 'creatorName',
  `superOrg_id` varchar(128) DEFAULT NULL comment '所属公司id',
  `superOrg_name` varchar(128) DEFAULT NULL comment '所属公司名称',
  `fulldept_id` varchar(128) DEFAULT NULL comment '全部门路径id',
  `fulldept_name` varchar(128) DEFAULT NULL comment '全部门路径名',
  `fullpost_id` varchar(128) DEFAULT NULL comment '全岗位路径id',
  `fullpost_name` varchar(128) DEFAULT NULL comment '全岗位路径名',
  `org_code` varchar(128) DEFAULT NULL comment '组织机构代码',
  `createTime` datetime DEFAULT NULL comment 'createTime',
  `modifiedTime` datetime DEFAULT NULL comment 'modifiedTime'
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
CREATE TABLE IF NOT EXISTS `materiel_releaselog` (
  `id` varchar(128) DEFAULT NULL comment 'id',
  `materiel_apply_id` varchar(128) DEFAULT NULL comment '物料申请id',
  `fafangren_id` varchar(128) DEFAULT NULL comment '发放人id',
  `fafang_time` datetime DEFAULT NULL comment '发放时间',
  `lingyongren_id` varchar(128) DEFAULT NULL comment '领用人id',
  `materiel_id` varchar(128) DEFAULT NULL comment '物资id',
  `chuhuo_warehouse_id` varchar(128) DEFAULT NULL comment '出货仓库id',
  `fafang_amount` decimal(15,2) DEFAULT NULL comment '发放数量',
  `delstatus` varchar(128) DEFAULT NULL comment 'delstatus',
  `creatorId` varchar(128) DEFAULT NULL comment 'creatorId',
  `creatorName` varchar(128) DEFAULT NULL comment 'creatorName',
  `superOrg_id` varchar(128) DEFAULT NULL comment '所属公司id',
  `superOrg_name` varchar(128) DEFAULT NULL comment '所属公司名称',
  `fulldept_id` varchar(128) DEFAULT NULL comment '全部门路径id',
  `fulldept_name` varchar(128) DEFAULT NULL comment '全部门路径名',
  `fullpost_id` varchar(128) DEFAULT NULL comment '全岗位路径id',
  `fullpost_name` varchar(128) DEFAULT NULL comment '全岗位路径名',
  `org_code` varchar(128) DEFAULT NULL comment '组织机构代码',
  `createTime` datetime DEFAULT NULL comment 'createTime',
  `modifiedTime` datetime DEFAULT NULL comment 'modifiedTime'
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
CREATE TABLE IF NOT EXISTS `baoxiao_application` (
  `id` varchar(128) DEFAULT NULL comment 'id',
  `baoxiao_number` varchar(128) DEFAULT NULL comment '报销单号',
  `baoxiao_id` varchar(128) DEFAULT NULL comment '报销人id',
  `baoxiao_time` datetime DEFAULT NULL comment '报销时间',
  `baoxiao_explain` varchar(128) DEFAULT NULL comment '报销说明',
  `baoxiao_jine` decimal(15,2) DEFAULT NULL comment '报销金额',
  `payment` varchar(128) DEFAULT NULL comment '支付',
  `state` varchar(128) DEFAULT NULL comment '状态',
  `examine` varchar(128) DEFAULT NULL comment '审核',
  `delstatus` varchar(128) DEFAULT NULL comment 'delstatus',
  `creatorId` varchar(128) DEFAULT NULL comment 'creatorId',
  `creatorName` varchar(128) DEFAULT NULL comment 'creatorName',
  `superOrg_id` varchar(128) DEFAULT NULL comment '所属公司id',
  `superOrg_name` varchar(128) DEFAULT NULL comment '所属公司名称',
  `fulldept_id` varchar(128) DEFAULT NULL comment '全部门路径id',
  `fulldept_name` varchar(128) DEFAULT NULL comment '全部门路径名',
  `fullpost_id` varchar(128) DEFAULT NULL comment '全岗位路径id',
  `fullpost_name` varchar(128) DEFAULT NULL comment '全岗位路径名',
  `org_code` varchar(128) DEFAULT NULL comment '组织机构代码',
  `createTime` datetime DEFAULT NULL comment 'createTime',
  `modifiedTime` datetime DEFAULT NULL comment 'modifiedTime'
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
CREATE TABLE IF NOT EXISTS `baoxiao_processlog` (
  `id` varchar(128) DEFAULT NULL comment 'id',
  `baoxiao_ApplyId` varchar(128) DEFAULT NULL comment '报销申请id',
  `chuliren_id` varchar(128) DEFAULT NULL comment '处理人id',
  `operation_time` datetime DEFAULT NULL comment '操作时间',
  `action` varchar(128) DEFAULT NULL comment '动作',
  `examine_opinion` varchar(128) DEFAULT NULL comment '审批意见',
  `delstatus` varchar(128) DEFAULT NULL comment 'delstatus',
  `creatorId` varchar(128) DEFAULT NULL comment 'creatorId',
  `creatorName` varchar(128) DEFAULT NULL comment 'creatorName',
  `superOrg_id` varchar(128) DEFAULT NULL comment '所属公司id',
  `superOrg_name` varchar(128) DEFAULT NULL comment '所属公司名称',
  `fulldept_id` varchar(128) DEFAULT NULL comment '全部门路径id',
  `fulldept_name` varchar(128) DEFAULT NULL comment '全部门路径名',
  `fullpost_id` varchar(128) DEFAULT NULL comment '全岗位路径id',
  `fullpost_name` varchar(128) DEFAULT NULL comment '全岗位路径名',
  `org_code` varchar(128) DEFAULT NULL comment '组织机构代码',
  `createTime` datetime DEFAULT NULL comment 'createTime',
  `modifiedTime` datetime DEFAULT NULL comment 'modifiedTime'
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
