CREATE TABLE IF NOT EXISTS `salary_adjustment` (
  `id` varchar(128) DEFAULT NULL comment 'id',
  `knight_id` varchar(128) DEFAULT NULL comment '骑士id',
  `subject` varchar(128) DEFAULT NULL comment '科目',
  `month` varchar(128) DEFAULT NULL comment '月份',
  `type` varchar(128) DEFAULT NULL comment '类型',
  `money` decimal(15,2) DEFAULT NULL comment '金额',
  `state` varchar(128) DEFAULT NULL comment '状态',
  `remarks` varchar(128) DEFAULT NULL comment '备注',
  `delstatus` varchar(128) DEFAULT NULL comment 'delstatus',
  `creatorId` varchar(128) DEFAULT NULL comment 'creatorId',
  `creatorName` varchar(128) DEFAULT NULL comment 'creatorName',
  `superOrg_id` varchar(128) DEFAULT NULL comment '所属公司id',
  `superOrg_name` varchar(128) DEFAULT NULL comment '所属公司名称',
  `fulldept_id` varchar(128) DEFAULT NULL comment '全部门路径id',
  `fulldept_name` varchar(128) DEFAULT NULL comment '全部门路径名',
  `fullpost_id` varchar(128) DEFAULT NULL comment '全岗位路径id',
  `fullpost_name` varchar(128) DEFAULT NULL comment '全岗位路径名',
  `org_code` varchar(128) DEFAULT NULL comment '组织机构代码',
  `createTime` datetime DEFAULT NULL comment 'createTime',
  `modifiedTime` datetime DEFAULT NULL comment 'modifiedTime'
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
CREATE TABLE IF NOT EXISTS `attendance_data` (
  `id` varchar(128) DEFAULT NULL comment 'id',
  `knight_id` varchar(128) DEFAULT NULL comment '骑士id',
  `effective_quantity` decimal(15,2) DEFAULT NULL comment '有效单量',
  `attendance_day` decimal(15,2) DEFAULT NULL comment '考勤天',
  `state` varchar(128) DEFAULT NULL comment '状态',
  `confirm` varchar(128) DEFAULT NULL comment '确认',
  `examine` varchar(128) DEFAULT NULL comment '审核',
  `head_ofoperation` varchar(128) DEFAULT NULL comment '区长操作',
  `financial_audit` varchar(128) DEFAULT NULL comment '财务审核',
  `change_reasons` varchar(128) DEFAULT NULL comment '更改考勤为1原因',
  `examine_reasons` varchar(128) DEFAULT NULL comment '审核不通过原因',
  `delstatus` varchar(128) DEFAULT NULL comment 'delstatus',
  `creatorId` varchar(128) DEFAULT NULL comment 'creatorId',
  `creatorName` varchar(128) DEFAULT NULL comment 'creatorName',
  `superOrg_id` varchar(128) DEFAULT NULL comment '所属公司id',
  `superOrg_name` varchar(128) DEFAULT NULL comment '所属公司名称',
  `fulldept_id` varchar(128) DEFAULT NULL comment '全部门路径id',
  `fulldept_name` varchar(128) DEFAULT NULL comment '全部门路径名',
  `fullpost_id` varchar(128) DEFAULT NULL comment '全岗位路径id',
  `fullpost_name` varchar(128) DEFAULT NULL comment '全岗位路径名',
  `org_code` varchar(128) DEFAULT NULL comment '组织机构代码',
  `createTime` datetime DEFAULT NULL comment 'createTime',
  `modifiedTime` datetime DEFAULT NULL comment 'modifiedTime'
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
