CREATE TABLE IF NOT EXISTS `receivable` (
  `id` varchar(128) DEFAULT NULL comment 'id',
  `receivable_number` varchar(128) DEFAULT NULL comment '应收款编号',
  `yard_id` varchar(128) DEFAULT NULL comment '所属堆场',
  `customer_id` varchar(128) DEFAULT NULL comment '客户id',
  `invoice_number` varchar(128) DEFAULT NULL comment '发票号码',
  `invoice_jine` decimal(15,2) DEFAULT NULL comment '发票金额',
  `yishou_jine` decimal(15,2) DEFAULT NULL comment '已收金额',
  `qiankuan_jine` decimal(15,2) DEFAULT NULL comment '欠款金额',
  `kaipiao_time` datetime DEFAULT NULL comment '开票时间',
  `yinshou_time` datetime DEFAULT NULL comment '应收时间',
  `remark` varchar(128) DEFAULT NULL comment '备注',
  `state` varchar(128) DEFAULT NULL comment '状态',
  `delstatus` varchar(128) DEFAULT NULL comment 'delstatus',
  `creatorId` varchar(128) DEFAULT NULL comment 'creatorId',
  `creatorName` varchar(128) DEFAULT NULL comment 'creatorName',
  `superOrg_id` varchar(128) DEFAULT NULL comment '所属公司id',
  `superOrg_name` varchar(128) DEFAULT NULL comment '所属公司名称',
  `fulldept_id` varchar(128) DEFAULT NULL comment '全部门路径id',
  `fulldept_name` varchar(128) DEFAULT NULL comment '全部门路径名',
  `fullpost_id` varchar(128) DEFAULT NULL comment '全岗位路径id',
  `fullpost_name` varchar(128) DEFAULT NULL comment '全岗位路径名',
  `org_code` varchar(128) DEFAULT NULL comment '组织机构代码',
  `createTime` datetime DEFAULT NULL comment 'createTime',
  `modifiedTime` datetime DEFAULT NULL comment 'modifiedTime'
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
